id: P005460
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18511
  title: བོད་ཁུལ་གྱི་འབྲུག་པ་བཀའ་བརྒྱུད་པའི་དགོན་སྡེ་ཁག་གི་ལོ་རྒྱུས་མདོར་བསྡུས་མེས་པོ་དགྱེས་པའི་མཆོད་སྤྲིན།
    དེབ་བཞི་པ།
  author: ''
  volumes:
    d04b2e9183414b94949d8115bf64d745:
      image_group_id: I8LS18513
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
