id: opecha:P005460
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18511
  title: བོད་ཁུལ་གྱི་འབྲུག་པ་བཀའ་བརྒྱུད་པའི་དགོན་སྡེ་ཁག་གི་ལོ་རྒྱུས་མདོར་བསྡུས་མེས་པོ་དགྱེས་པའི་མཆོད་སྤྲིན།
    དེབ་བཞི་པ།
  volume: ''
  author: ''
