id: I69EBB0E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:39:15+00:00'
last_modified: '2022-06-08T03:14:33.187990+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18511
  title: བོད་ཁུལ་གྱི་འབྲུག་པ་བཀའ་བརྒྱུད་པའི་དགོན་སྡེ་ཁག་གི་ལོ་རྒྱུས་མདོར་བསྡུས་མེས་པོ་དགྱེས་པའི་མཆོད་སྤྲིན།
    དེབ་བཞི་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    889C:
      image_group_id: I8LS18513
      title: ''
      total_pages: 324
      order: 1
      base_file: 889C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
